# -*- coding: utf-8 -*-
"""regresijaEmocijaIzJednostanogTeksta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p4il_9eqfUqlgcH58Mqop85-eIrxn6Wm

Cilj projekta:
Napraviti model koji na osnovu jednostavnih rečenica (npr. "Bilo je super!", "Mrzim ponedeljak...") predviđa emocionalni ton poruke kao broj u rasponu od -1 do +1:

-1 znači jako negativna emocija,

0 je neutralno,

+1 je jako pozitivna emocija.

Model:
Koristićemo LSTM (Long Short-Term Memory) mrežu za regresiju:

Arhitektura:
Embedding sloj: Pretvara reči u vektore.

LSTM sloj: Uči kontekst i redosled reči.

Dense sloj: Izlazna vrednost – jedan broj (emocionalna vrednost između -1 i +1).

Pretprocesiranje podataka
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# Učitavanje podataka
df = pd.read_csv("emotion_dataset_large.csv")

# Podešavanja
MAX_VOCAB_SIZE = 5000
MAX_SEQUENCE_LENGTH = 15  # max broj reči u rečenici
EMBEDDING_DIM = 64

# Podela na X (tekst) i y (emocionalni skor)
X = df["text"].values
y = df["label"].values

# Tokenizacija
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(X)
word_index = tokenizer.word_index

# Pretvori tekst u sekvence
sequences = tokenizer.texts_to_sequences(X)
padded_sequences = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH, padding='post', truncating='post')

# Podela na trening i test skup
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, y, test_size=0.2, random_state=42)

print(f"Veličina trening skupa: {X_train.shape}")
print(f"Primer rečenice: {df['text'].iloc[0]}")
print(f"Tokeni: {sequences[0]}")

"""LSTM model za regresiju

Prima kao ulaz sekvencu tokena (rečenica),

Koristi Embedding sloj da pretvori reči u vektore,

Koristi LSTM sloj da nauči redosled reči,

Ima izlazni Dense sloj sa 1 neuron (za vrednost emocije) i linearnom aktivacijom jer je regresija.
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# Parametri
MAX_VOCAB_SIZE = 5000
MAX_SEQUENCE_LENGTH = 15
EMBEDDING_DIM = 64

# Model
model = Sequential([
    Embedding(input_dim=MAX_VOCAB_SIZE, output_dim=EMBEDDING_DIM, input_length=MAX_SEQUENCE_LENGTH),
    LSTM(64, return_sequences=False),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # regresija → linear
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])  # MSE = Mean Squared Error

model.summary()

#treniranje modela
history = model.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=15,
    batch_size=32,
    verbose=1
)

"""Evaluacija i vizuelizacija:"""

import matplotlib.pyplot as plt

# Loss
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Val Loss')
plt.title('Loss over epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss (MSE)')
plt.legend()
plt.grid(True)
plt.show()

# MAE
plt.plot(history.history['mae'], label='Train MAE')
plt.plot(history.history['val_mae'], label='Val MAE')
plt.title('Mean Absolute Error over epochs')
plt.xlabel('Epoch')
plt.ylabel('MAE')
plt.legend()
plt.grid(True)
plt.show()

#Evaluacija na test skupu
test_loss, test_mae = model.evaluate(X_test, y_test, verbose=0)
print(f"Test MSE: {test_loss:.4f}")
print(f"Test MAE: {test_mae:.4f}")

#stvarne vs predvidjene vrednosti scatter plot
# Predikcija
y_pred = model.predict(X_test).flatten()

# Scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.xlabel("Stvarna emocionalna vrednost")
plt.ylabel("Predviđena vrednost")
plt.title("Stvarna vs. predviđena emocionalna ocena")
plt.grid(True)
plt.plot([-1, 1], [-1, 1], 'r--')  # dijagonala
plt.show()

# Testiranje  na novim recenicama

def predict_emotion(text):
    seq = tokenizer.texts_to_sequences([text])
    padded = pad_sequences(seq, maxlen=MAX_SEQUENCE_LENGTH, padding='post')
    pred = model.predict(padded)[0][0]
    return round(pred, 2)

# Primeri
examples = [
    "I hate everything about this.",
    "It was a beautiful moment.",
    "I'm not sure how I feel.",
    "Today was fine.",
    "Absolutely amazing!"
]

for text in examples:
    print(f"{text} → Predikcija: {predict_emotion(text)}")

"""Napredne ideje za prosirenje projekta"""

# Dodajemo Bidirectional sloj da model bolje
#razume kontekst iz obe strane rečenice (i unapred i unazad).

#🔹 Prednost: bolje hvatanje nijansi u rečenicama tipa: "I am not unhappy".

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

# Novi model sa Bidirectional LSTM
model_bi = Sequential([
    Embedding(input_dim=MAX_VOCAB_SIZE, output_dim=EMBEDDING_DIM, input_length=MAX_SEQUENCE_LENGTH),
    Bidirectional(LSTM(64, return_sequences=False)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # regresija
])

model_bi.compile(optimizer='adam', loss='mse', metrics=['mae'])
model_bi.summary()

#treniranj bidirectional modela:
history_bi = model_bi.fit(
    X_train, y_train,
    validation_split=0.2,
    epochs=15,
    batch_size=32,
    verbose=1
)

#Evaluacija bidirectional modela:

# Evaluacija
test_loss_bi, test_mae_bi = model_bi.evaluate(X_test, y_test, verbose=0)
print(f"Bidirectional LSTM - Test MSE: {test_loss_bi:.4f}")
print(f"Bidirectional LSTM - Test MAE: {test_mae_bi:.4f}")

#vizuelizacija bidirectional modela:

# Loss
plt.plot(history_bi.history['loss'], label='Train Loss')
plt.plot(history_bi.history['val_loss'], label='Val Loss')
plt.title('Bidirectional LSTM - Loss')
plt.xlabel('Epoch')
plt.ylabel('MSE Loss')
plt.legend()
plt.grid(True)
plt.show()

# MAE
plt.plot(history_bi.history['mae'], label='Train MAE')
plt.plot(history_bi.history['val_mae'], label='Val MAE')
plt.title('Bidirectional LSTM - MAE')
plt.xlabel('Epoch')
plt.ylabel('Mean Absolute Error')
plt.legend()
plt.grid(True)
plt.show()

"""Attention mehanizam
Dodavanje "attention" sloja koji pomaže modelu da fokusira pažnju na bitne delove rečenice.

📦 Možemo ručno definisati attention sloj ili koristiti keras-nlp ili transformers.

Primer jednostavnog attention wrappera možemo dodati kasnije ako želiš — ili možemo ići ka Transformer modelima.

3. Klasifikacija pored regresije (dual task)
Model može istovremeno da:

Predviđa tačnu vrednost emocije (regresija)

Predviđa klasu (negativno, neutralno, pozitivno)

➡️ Multitask learning – dodajemo još jedan izlazni sloj:
"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Dropout

input_layer = Input(shape=(MAX_SEQUENCE_LENGTH,))
x = Embedding(MAX_VOCAB_SIZE, EMBEDDING_DIM)(input_layer)
x = LSTM(64)(x)
x = Dropout(0.3)(x)

reg_output = Dense(1, activation='linear', name='regression')
class_output = Dense(3, activation='softmax', name='classification')  # 3 klase

model = Model(inputs=input_layer, outputs=[reg_output(x), class_output(x)])

model.compile(
    optimizer='adam',
    loss={'regression': 'mse', 'classification': 'sparse_categorical_crossentropy'},
    metrics={'regression': 'mae', 'classification': 'accuracy'}
)

"""4. Prikaz pogrešnih predikcija
Prikazati primere gde je razlika između stvarne i predviđene vrednosti najveća.
"""

errors = np.abs(y_test - y_pred)
top_errors = np.argsort(errors)[-5:]

for i in top_errors:
    print(f"Tekst: {X_test[i]}")
    print(f"Stvarno: {y_test[i]}, Predikcija: {y_pred[i]:.2f}, Greška: {errors[i]:.2f}")
    print("------")